### ISSUE TITLE
Spotlight Performances / Possible tuning ?

### ISSUE THREAD

**Issue by Skunnyk** [dbpedia-spotlight/dbpedia-spotlight-model#3]
Hi,
I'm working on an "in-house" dbpedia-spotlight setup.
I use dbpedia-spotlight-1.0.0.jar, the en.tar.gz model from http://downloads.dbpedia-spotlight.org/2016-04/en/model/en.tar.gz, and start with : 

`java -Xms10G -Xmx10G -jar dbpedia-spotlight-1.0.0.jar en_2+2/ http://x.x.x.x:2222/en/ `

- Server bare metal
- 16 core CPUs ( CPU E5-2620  )
- 16GB ram

From my firsts benchmarks with random english articles with a confidence=0.35, I can't go beyond 30req/s. With confidence=0.5, around 60req/s. It seems the number of // clients does not matter, I'm still 'stuck' at 30 req/s.
I also tried on another hardware/aws etc, and still the same result.
Is there is some known limitations ? 
Spotlight seems to use at maximum 8 cores. Is any tuning possible ? I can't see any documentation on this part.

Thank you :)

**Comment by Skunnyk** [comment]
Oh, and java 1.8 :)

**Comment by Skunnyk** [comment]
Ok, so after more tests/digging : 
spotlight only uses 5 CPUs at a time from what I see.
It uses grizzly for http, and in https://github.com/javaee/grizzly/blob/master/modules/grizzly/src/main/java/org/glassfish/grizzly/threadpool/AbstractThreadPool.java#L79 we can see a "hard" limit to 5 threads, maybe it's related ?
Btw I can't find a way to modify this parameter from spotlight.

**Comment by sandroacoelho** [comment]
Hi @Skunnyk ,
@tgalery (Spotlight developer) has opened an issue related [here](https://github.com/dbpedia-spotlight/dbpedia-spotlight/issues/217).  This subject has not got much attention until the people started to use Spotlight under Apache UIMA and other environments that require massive parallel processing.

We are currently working on to solve a problem regarding with our models for Eastern language (Chinese and Japanese). Our next task will bring reactive style to our REST, that will deal better with these new requirements.

Best,

**Comment by Skunnyk** [comment]
Thank you @sandroacoelho
So, if I understand, for now, we know that there is some concurrency problems but don't know the real limits / how to handle that ?
ATM, If I want to handle say 150queries/s, the only way is to shard and use multiple spotlight instances ?

**Comment by tgalery** [comment]
@Skunnyk probably (and putting a load balancer in front of them). To be honest, the server and concurrency libraries used by the project are insanely out dated. If we were to actually devise time to tackle that, we probably would change it completely.

**Comment by sandroacoelho** [comment]
Hi @Skunnyk , @tgalery 

For now, I advise you use multiple instances through a load balance using Apache or Nginx.
I make @tgalery words my own.  I believe that on next few weeks we can plan and do a big upgrade to solve this issue.

Best,

**Comment by Skunnyk** [comment]
Thank you guys, that's what I thought.
So let's go for a load balancing with multiples instances.
Good luck for the next steps !
