### ISSUE TITLE
Response 414 - "REQUEST URI TOO LARGE"

### ISSUE THREAD

**Issue by dustyny** [dbpedia-spotlight/dbpedia-spotlight-model#32]
I'm getting an error that I'm passing in a document that is to large for Spotlight. 

I'm using the python requests module. The document that I'm trying to pass in has 2533 words. I've cleaned it of stop words and sanitized it pretty well. When I cut the document down to 1211 words it works without any issues. 

EDIT: I totally forgot that GET has a URL length limit. Is there any way to use a POST? 

querystring = {"text": text}
headers = {
    'accept': "application/json",
    'Cache-Control': "no-cache"
    }
response = requests.request("GET", url, headers=headers, params=querystring)

Are there any workarounds? 
[examplelarge.txt](https://github.com/dbpedia-spotlight/dbpedia-spotlight-model/files/2259751/examplelarge.txt)

**Comment by sandroacoelho** [comment]
Try to use "POST" instead

**Comment by dustyny** [comment]
Could you please explain how the post is supposed to be constructed? I don't see any mention of it in the documentation and when I try I'm getting an error response.

**Comment by dustyny** [comment]
Yes got that.. This is missing from the documentation on the main site. 
https://www.dbpedia-spotlight.org/api
I found the answer on the old github repository. Which is marked "No longer in active development".  It was a bit confusing. 

https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Web-service


```
import requests
url = "http://localhost/rest/annotate"

payload = "confidence=0.5&support=20&text=Donald%20Trump%20said%20on%20Twitter"
headers = {
    'Accept': "application/json",
    'Content-Type': "application/x-www-form-urlencoded"
    }

response = requests.request("POST", url, data=payload, headers=headers)
```

print(response.text)
