### ISSUE TITLE
Dutch Spotlight down

### ISSUE THREAD

**Issue by nicky508** [dbpedia-spotlight/dbpedia-spotlight-model#35]
For some reason the dutch spotlight service seems to be down (http://api.dbpedia-spotlight.org/nl/annotate).

> Service Unavailable. 
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Is this planned and will it be back online in the future?

**Comment by sandroacoelho** [comment]
Hi @nicky508 ,

Unfortunately, our demo is available in English, German (Supported by https://www.uni-mannheim.de/) and Portuguese (Supported by https://www.rnp.br/en).

I was paying from my money to keep some instances online, such as Dutch, Spanish, Italian, and others, but now I can't do that. Sorry.

However, you can run it in your local machine, via [Docker](https://github.com/dbpedia-spotlight/spotlight-docker).

Best,
