### ISSUE TITLE
How to identify the detected resource in the input text from json response 

### ISSUE THREAD

**Issue by fanavarro** [dbpedia-spotlight/dbpedia-spotlight-model#47]
Hi, I am wondering how to relate detected resources with the input text. For example, for the input:
"The Battle of Gettysburg was fought July 1–3, 1863."
I used the following curl command to query a local instance of spotlight:

`curl -X POST   http://localhost:2222/rest/annotate   -H 'accept: application/json'   -H 'content-type: application/x-www-form-urlencoded'   --data-urlencode "text=The Battle of Gettysburg was fought July 1–3, 1863."   --data-urlencode "confidence=0.35"`

Which returns the following:
```
{
   "@text":"The Battle of Gettysburg was fought July 1–3, 1863.",
   "@confidence":"0.35",
   "@support":"0",
   "@types":"",
   "@sparql":"",
   "@policy":"whitelist",
   "Resources":[
      {
         "@URI":"http://dbpedia.org/resource/Battle_of_Gettysburg",
         "@support":"2871",
         "@types":"Wikidata:Q1656682,DUL:Event,Schema:Event,DBpedia:SocietalEvent,DBpedia:MilitaryConflict,DBpedia:Event",
         "@surfaceForm":"Gettysburg",
         "@offset":"14",
         "@similarityScore":"0.9856069793346309",
         "@percentageOfSecondRank":"0.014354886850971043"
      }
   ]
}
```
From this response, how can I know that the URI <http://dbpedia.org/resource/Battle_of_Gettysburg> comes from the text "The Battle of Gettysburg"? I was using the surface form, but this field only indicates "Gettysburg". Also, the offset field indicates the start position of "Gettysburg". Could this be a bug?

I've tried to use the demo webpage (https://www.dbpedia-spotlight.org/demo/) in order to check if only "Gettysburg" is hightlighed, but it seems to be down at this moment.

Thanks beforehand.

**Comment by ghost** [comment]
I'm afraid I won't be able to help you with your issue, but the demo is available under: https://demo.dbpedia-spotlight.org/

**Comment by fanavarro** [comment]
Hi @lisabecker-ml6, thanks for your answer. I've cheked it in the demo and the behaviour is the same; only the word "Gettysburg" is annotated as "Battle of Gettysburg":
![imagen](https://user-images.githubusercontent.com/11376639/197497171-0aeb779f-e63f-4404-aacd-0363ccd1f49a.png)
So maybe it is a problem with the models. I am closing the issue as we've confirmed this.

**Comment by chrishokamp** [comment]
hi Francisco, this annotation means that the model annotated the surface
form "Gettysburg" as the entity "Battle of Gettysburg".
The model didn't recognize (aka "spot") the string "Battle of Gettysburg",
it spotted "Gettysburg", and linked it to the entity "Battle of Gettysburg"
does that make sense?

**Comment by fanavarro** [comment]
Hi @chrishokamp, thanks for your answer.

For me, if the model spots the string "Gettysburg", that word should be linked to the entity <[https://dbpedia.org/resource/Gettysburg,_Pennsylvania](https://dbpedia.org/resource/Gettysburg,_Pennsylvania)>, which is a location. Otherwise, if the model recognises the string "Battle of Gettysburg", the corresponding entity should be <[http://dbpedia.org/resource/Battle_of_Gettysburg](http://dbpedia.org/resource/Battle_of_Gettysburg)>, which is an historic event that happened in the location of Gettysburg.

At the moment, the model is linking a string representing a location ("Gettysburg") to an entity representing an historical event happened in that location (<[http://dbpedia.org/resource/Battle_of_Gettysburg](http://dbpedia.org/resource/Battle_of_Gettysburg)>).

I am reopening the issue if you want to discuss this behavior, but actually I only wanted to be sure that this little mistake was not in my side while using curl to retrieve the information via REST. I understand that the underlying NLP models are complex, and trying to fix each special case is normally not achievable, so feel free to close this issue.

Kind regards,
Fran.

**Comment by chrishokamp** [comment]
ok, in this context it's debatable, but I understand your expectation that
the entire surface form would be annotated instead of just "Gettysburg",
this is one of the many fun/complex/annoying things about the entity
linking task, i think you can close the issue :-)

**Comment by fanavarro** [comment]
Thanks for your answer, @chrishokamp, I'm closing the issue.
