### ISSUE TITLE
Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile

### ISSUE THREAD

**Issue by Shivangini-G** [dbpedia-spotlight/dbpedia-spotlight-model#52]
**mvn install -rf :core -U -e**
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ core ---
[WARNING]  Expected all dependencies to require Scala version: 2.13.5
[WARNING]  org.dbpedia.extraction:core:3.9 requires scala version: 2.13.5
[WARNING]  net.liftweb:lift-json_2.10:2.5 requires scala version: 2.13.5
[WARNING]  net.liftweb:lift-json_2.10:2.5 requires scala version: 2.10.0
[WARNING] Multiple versions of scala libraries detected!
[INFO] /Users/shivanginigugalia/dbpedia-spotlight-model/core/src/main/java:-1: info: compiling
[INFO] /Users/shivanginigugalia/dbpedia-spotlight-model/core/src/main/scala:-1: info: compiling
[INFO] Compiling 194 source files to /Users/shivanginigugalia/dbpedia-spotlight-model/core/target/classes at 1615878079059
[ERROR] /Users/shivanginigugalia/dbpedia-spotlight-model/core/src/main/scala/com/officedepot/cdap2/collection/CompactHashMap.scala:47: error: not found: type ClassManifest
[ERROR] class CompactHashMap[K: ClassManifest, V: ClassManifest] () extends scala.collection.mutable.Map[K,V] with Serializable {
[ERROR]                         ^
[ERROR] /Users/shivanginigugalia/dbpedia-spotlight-model/core/src/main/scala/com/officedepot/cdap2/collection/CompactHashMap.scala:47: error: not found: type ClassManifest
[ERROR] class CompactHashMap[K: ClassManifest, V: ClassManifest] () extends scala.collection.mutable.Map[K,V] with Serializable {
[ERROR]                                           ^
...
...
[WARNING] 5 warnings
[ERROR] 107 errors
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for DBpedia Spotlight Core 1.0:
[INFO] 
[INFO] DBpedia Spotlight Core ............................. FAILURE [ 49.191 s]
[INFO] DBpedia Spotlight RESTful API ...................... SKIPPED
[INFO] DBpedia Spotlight Indexing ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.297 s
[INFO] Finished at: 2021-03-16T12:31:25+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project core: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.2.2:compile (scala-compile-first) on project core: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**If I remove scala-compile-first, then this error m getting:**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTag

**Comment by Julio-Noe** [comment]
Hello @Shivangini-G,

I reproduced your problem and I get a similar error. The dbpedia-spotlight-model project is base on JDK 8 then, some features of this JDK are needed to compile the project (up versions of JDK do not contain some libraries). To fix this error I download the JDK8 and define the JAVA_HOME to the corresponding directory, for example:

     export JAVA_HOME=/home/user/.../jdk1.8.0.....

After this, the compilation was successful.

**Comment by Shivangini-G** [comment]
I downloaded JDK8 and set the JAVA_HOME but still getting the same errors.
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project core: Compilation failure
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

I changed the scala version in pom file from 2.10.4 to 2.13.5.... can that be an issue too?

**Comment by Shivangini-G** [comment]
The error got resolved, I am able to compile and successfully run the curl cmd too.

**Comment by fishermanxzx** [comment]
how to fix it?
